variables:
  myInitials: 'jb' # Lower case initials
  coreInfrastructureName: 'visma-demo-app-$(myInitials)-$(Environment.Name)'
  webAppName: '$(coreInfrastructureName)'
  stagingResourceGroupName: 'visma-demo-app-stg'
  stagingStorageAccountName: 'vimsademoappstg$(myInitials)'
  poolName: 'windows-latest'
  System.Debug: 'false'
  azureSubscriptionName: 'jb-visual-studio-professional'
  resourceGroupName: 'visma-demo-app-$(myInitials)'
  armTemplateParameters: '-_artifactsLocation $(artifactsLocation) -_artifactsLocationSasToken "$(artifactsLocationSasToken)" -coreInfrastructureName $(coreInfrastructureName) -webAppName $(webAppName)'

# GitHub Repo that conatins build templates. Reference https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=vsts#using-other-repositories
resources:
  repositories:
  - repository: azureDevOpsTemplates
    type: github
    name: janisBerz/rac-azure-devops-templates
    endpoint: 'github.com_janisBerz'
    ref: buildpackage-only  # optional ref to pin to

stages:
- stage: Build
  jobs:
  - template: jobs/dotNetCore.yml@azureDevOpsTemplates # Template reference
    parameters:
      webAppName: $(webAppName)
